module.exports = {
    NEW_SEARCH_INPUT:'NEW_SEARCH_INPUT',
    DEFINE_REPOSITORY_SEARCH_ARRAY:'DEFINE_REPOSITORY_SEARCH_ARRAY',
    SELECT_PAGE:'SELECT_PAGE',
    UPDATE_TOTAL_RESULT_COUNT:'UPDATE_TOTAL_RESULT_COUNT',
    NEED_GET_CONTRIBUTORS:'NEED_GET_CONTRIBUTORS',
    DEFINE_CONTRIBUTORS:'DEFINE_CONTRIBUTORS',


};


